kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 127.0.0.1
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service
