kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: daniilkorotaev/spring-kafka-try-out:13.0
          ports:
            - containerPort: 8080