apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  labels:
    name: spring-app-service
spec:
  ports:
    - port: 8080
      name: spring-app-port
      protocol: TCP
  selector:
    app: spring-app